<!-- Js Plugins -->
<script src="{{ asset('assets/frontend/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('assets/frontend/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/frontend/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('assets/frontend/js/mixitup.min.js') }}"></script>
<script src="{{ asset('assets/frontend/js/masonry.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/frontend/js/jquery.slicknav.js') }}"></script>
<script src="{{ asset('assets/frontend/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('assets/frontend/js/main.js') }}"></script>